<a href="https://colab.research.google.com/github/MrChelas/data-analytics-project-100/blob/main/steps_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Шаг 1. Подключаем библиотеки и первичные df

In [ ]:
import pandas as pd
import requests

## Создаем датафреймы из гугл таблиц

In [27]:
df_reg = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vT6rMyy3TfzrEheBOwlgts_SHTc67b_a8NsuSsfVnH6nI8x9zb9vt11gbMk1fWn4j3jvBxq9yqzPdhN/pub?gid=63066832&single=true&output=csv')

In [30]:
df_vis = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTC3r0B_geUBpk7soZCc03xDVzUBGMS__ZxPocgPQPmQ3guoVx9sXmNWwL2_vBHIFHVR_GDr4qlL5dH/pub?gid=1866591177&single=true&output=csv')

## Сводка общей информации по датафреймам

In [32]:
df_reg.describe()

            user_id
count  1.000000e+03
mean   4.488623e+06
std    2.620568e+06
min    2.236800e+04
25%    2.235489e+06
50%    4.473044e+06
75%    6.779707e+06
max    8.881772e+06

In [33]:
df_vis.describe()

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01 8:01:45
freq,4,954,71,2

In [40]:
#просмотр текущих переменных. Удалить можно через del (имя)
%whos

Variable   Type         Data/Info
---------------------------------
df         DataFrame                        date <...>\n[1000 rows x 5 columns]
df2        DataFrame                             <...>\n[1000 rows x 4 columns]
df_reg     DataFrame                        date <...>\n[1000 rows x 5 columns]
df_vis     DataFrame                             <...>\n[1000 rows x 4 columns]
pd         module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
requests   module       <module 'requests' from '<...>es/requests/__init__.py'>
url        str          https://docs.google.com/s<...>n4j3jvBxq9yqzPdhN/pubhtml

# Шаг 2. Подключение по API

In [51]:
r_visits = requests.get('https://data-charts-api.hexlet.app/visits?begin=2023-03-01&end=2023-09-01')

In [50]:
r_regs = requests.get('https://data-charts-api.hexlet.app/registrations?begin=2023-03-01&end=2023-09-01')

In [53]:
df_api_visits = pd.DataFrame(r_visits.json())
df_api_regs = pd.DataFrame(r_regs.json())